### ISSUE TITLE
Reactive counts using Publish scoped counts method 

### ISSUE THREAD

**Issue by frankwo1** [nate-strauser/meteor-publish-performant-counts#5]
Hi Nate, 
I'm using Publish scoped counts method -
Meteor.publish('countPublish', function(someValue) {
  return new Counter('countCollection', Collection.find({
  	someField: someValue
  }));
});

Passing "this.params._id" from iron router (subscribe('countPublish', this.params._id)
I don't know how to make this reactive 

- I have tried to use add peerlibrary:reactive-publish - doesnt work
Meteor.publish('countPublish', function() {
  this.autorun(function (someValue) {
  var accepteds = Collection.find({
  	someField: someValue
  });
  return new Counter('countPublish', accepteds);
 });
});

Any suggestions - Thanks for your help
Frank

**Comment by evolross** [comment]
You shouldn't need to use reactive-publish... this package alone should return a reactive count.  You might be doing something wrong. Do you have a small repo to share that reproduces the problem?  BTW, this package hasn't had a commit in a year and a half.  So it's not really maintained.

**Comment by frankwo1** [comment]
OK, let me put something up - re: Year +1/2 - yeah, I realize that, although I thought it must still be working since its a part of weworkmeteor

**Comment by nate-strauser** [comment]
Please do provide more details.  This package is still in use and works
well for me.

On Aug 1, 2018 2:12 PM, "FrankWo1" <notifications@github.com> wrote:

OK, let me put something up - re: Year +1/2 - yeah, I realize that,
although I thought it must still be working since its a part of weworkmeteor

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/nate-strauser/meteor-publish-performant-counts/issues/5#issuecomment-409669890>,
or mute the thread

**Comment by frankwo1** [comment]
Hi Guys,
Thanks - I solved it. Please correct me if Im wrong

- I am using the "Server Scoped Counts" and getting counts of a second related collection (using tag: this.params._id) 
- Since Meteor Publish is NOT reactive, these counts were not updating when I switched to a new route /:_id.
- I was initially trying to place autorun in the iron:router but this does not work 
- I have placed autorun as a template helper and it updates the counts immediately

Template.accepteds.onCreated(function created() {
    this.autorun(() => {
        Meteor.subscribe('Counted', Router.current().params._id);
    });
});
